# Generated by Django 3.0.1 on 2019-12-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('verified_by_planner', models.BooleanField()),
                ('verified_by_participant', models.BooleanField()),
                ('status', models.CharField(choices=[('o', 'Open'), ('p', 'Process'), ('d', 'Done')], max_length=1)),
                ('deadline', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='eventapp.User')),
                ('supporters', models.ManyToManyField(related_name='supporters', to='eventapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('events', models.ManyToManyField(to='eventapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Forumentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='eventplanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='eventapp.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(related_name='invited', to='eventapp.User'),
        ),
    ]
