# Generated by Django 3.0.1 on 2020-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20200103_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='supporters',
            field=models.ManyToManyField(null=True, related_name='supporters', to='eventapp.User'),
        ),
    ]
