# Generated by Django 3.0.1 on 2020-01-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20200103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='invited', to='eventapp.User'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='events',
            field=models.ManyToManyField(blank=True, to='eventapp.Event'),
        ),
    ]
