# Generated by Django 3.0.1 on 2020-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20200103_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='supporters',
            field=models.ManyToManyField(blank=True, null=True, related_name='supporters', to='eventapp.User'),
        ),
    ]
