# Generated by Django 2.2.7 on 2020-01-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20200103_1402'),
        ('eventapp', '0004_auto_20200103_1355'),
    ]

    operations = [
    ]
