# Generated by Django 2.2.7 on 2020-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_merge_20200106_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supporters', to='eventapp.User'),
        ),
    ]
