# Generated by Django 2.2.7 on 2020-01-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_auto_20200106_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='eventapp.Event'),
        ),
    ]
